In [2]:
import pandas as pd

dataset_urls = {
    "legacy_2020_2024": (
        "https://data.lacity.org/resource/2nrs-mtv8.csv?$limit=5"
    ),
    "nibrs_2024_2025": (
        "https://data.lacity.org/resource/y8y3-fqfu.csv?$limit=5"
    ),
    "nibrs_2026_present": (
        "https://data.lacity.org/resource/k7nn-b2ep.csv?$limit=5"
    ),
}

In [3]:
samples = {}

for dataset_name, url in dataset_urls.items():
    samples[dataset_name] = pd.read_csv(url)

    print(f"\n{dataset_name}")
    print("Shape:", samples[dataset_name].shape)
    print("Columns:")
    print(samples[dataset_name].columns.tolist())

legacy_2020_2024
Shape: (5, 28)
Columns:
['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name', 'rpt_dist_no', 'part_1_2', 'crm_cd', 'crm_cd_desc', 'mocodes', 'vict_age', 'vict_sex', 'vict_descent', 'premis_cd', 'premis_desc', 'weapon_used_cd', 'weapon_desc', 'status', 'status_desc', 'crm_cd_1', 'crm_cd_2', 'crm_cd_3', 'crm_cd_4', 'location', 'cross_street', 'lat', 'lon']

nibrs_2024_2025
Shape: (5, 31)
Columns:
['caseno', 'uniquenibrno', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name', 'rpt_dist_no', 'totaloffensecount', 'group', 'nibr_code', 'nibr_description', 'crime_against', 'premis_cd', 'premis_desc', 'weapon_used_cd', 'weapon_desc', 'status', 'status_desc', 'totalvictimcount', 'victim_shot', 'domestic_violence_crime', 'hate_crime', 'gang_related_crime', 'transit_related_crime', 'homeless_victim_crime', 'homeless_suspect_crime', 'homeless_arrestee_crime', 'location', 'lat', 'lon']

nibrs_2026_present
Shape: (5, 31)
Columns:
['caseno', 'uniquenibrno', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name', 'rpt_dist_no', 'totaloffensecount', 'group', 'nibr_code', 'nibr_description', 'crime_against', 'premis_cd', 'premis_desc', 'weapon_used_cd', 'weapon_desc', 'status', 'status_desc', 'totalvictimcount', 'victim_shot', 'domestic_violence_crime', 'hate_crime', 'gang_related_crime', 'transit_related_crime', 'homeless_victim_crime', 'homeless_suspect_crime', 'homeless_arrestee_crime', 'hndrdth_loc_chk', 'hndrdth_lat', 'hndrdth_lon']

In [4]:
for dataset_name, df in samples.items():
    print(f"\n{dataset_name}")

    schema_summary = pd.DataFrame({
        "column_name": df.columns,
        "sample_dtype": df.dtypes.astype(str).values,
        "non_null_values": df.notna().sum().values
    })

    display(schema_summary)

legacy_2020_2024

       column_name sample_dtype  non_null_values
0            dr_no        int64                5
1        date_rptd          str                5
2         date_occ          str                5
3         time_occ        int64                5
4             area        int64                5
5        area_name          str                5
6      rpt_dist_no        int64                5
7         part_1_2        int64                5
8           crm_cd        int64                5
9      crm_cd_desc          str                5
10         mocodes          str                5
11        vict_age        int64                5
12        vict_sex          str                5
13    vict_descent          str                5
14       premis_cd        int64                5
15     premis_desc          str                5
16  weapon_used_cd      float64                1
17     weapon_desc          str                1
18          status          str                5
19     status_desc          str                5
20        crm_cd_1        int64                5
21        crm_cd_2      float64                0
22        crm_cd_3      float64                0
23        crm_cd_4      float64                0
24        location          str                5
25    cross_street          str                1
26             lat      float64                5
27             lon      float64                5

nibrs_2024_2025

                column_name sample_dtype  non_null_values
0                    caseno        int64                5
1              uniquenibrno          str                5
2                 date_rptd          str                5
3                  date_occ          str                5
4                  time_occ        int64                5
5                      area        int64                5
6                 area_name          str                5
7               rpt_dist_no        int64                5
8         totaloffensecount        int64                5
9                     group          str                5
10                nibr_code          str                5
11         nibr_description          str                5
12            crime_against          str                5
13                premis_cd          str                5
14              premis_desc          str                5
15           weapon_used_cd      float64                1
16              weapon_desc          str                1
17                   status        int64                5
18              status_desc          str                5
19         totalvictimcount        int64                5
20              victim_shot          str                5
21  domestic_violence_crime          str                5
22               hate_crime          str                5
23       gang_related_crime          str                5
24    transit_related_crime          str                5
25    homeless_victim_crime          str                5
26   homeless_suspect_crime          str                5
27  homeless_arrestee_crime          str                5
28                 location          str                5
29                      lat      float64                5
30                      lon      float64                5

nibrs_2026_present

                column_name sample_dtype  non_null_values
0                    caseno        int64                5
1              uniquenibrno          str                5
2                 date_rptd          str                5
3                  date_occ          str                5
4                  time_occ        int64                5
5                      area        int64                5
6                 area_name          str                5
7               rpt_dist_no        int64                5
8         totaloffensecount        int64                5
9                     group          str                5
10                nibr_code          str                5
11         nibr_description          str                5
12            crime_against          str                5
13                premis_cd          str                5
14              premis_desc          str                5
15           weapon_used_cd      float64                3
16              weapon_desc          str                3
17                   status        int64                5
18              status_desc          str                5
19         totalvictimcount        int64                5
20              victim_shot          str                5
21  domestic_violence_crime          str                5
22               hate_crime          str                5
23       gang_related_crime          str                5
24    transit_related_crime          str                5
25    homeless_victim_crime          str                5
26   homeless_suspect_crime          str                5
27  homeless_arrestee_crime          str                5
28          hndrdth_loc_chk          str                5
29              hndrdth_lat      float64                5
30              hndrdth_lon      float64                5

In [5]:
display(samples["legacy_2020_2024"].head(2).T)

,0,1
dr_no,211507896,201516622
date_rptd,2021-04-11T00:00:00.000,2020-10-21T00:00:00.000
date_occ,2020-11-07T00:00:00.000,2020-10-18T00:00:00.000
time_occ,845,1845
area,15,15
area_name,N Hollywood,N Hollywood
rpt_dist_no,1502,1521
part_1_2,2,1
crm_cd,354,230
crm_cd_desc,THEFT OF IDENTITY,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT"
mocodes,0377,0416 0334 2004 1822 1414 0305 0319 0400
vict_age,31,32
vict_sex,M,M
vict_descent,H,H
premis_cd,501,102
premis_desc,SINGLE FAMILY DWELLING,SIDEWALK
weapon_used_cd,NaN,200.0
weapon_desc,NaN,KNIFE WITH BLADE 6INCHES OR LESS
status,IC,IC
status_desc,Invest Cont,Invest Cont
crm_cd_1,354,230
crm_cd_2,NaN,NaN
crm_cd_3,NaN,NaN
crm_cd_4,NaN,NaN
location,7800 BEEMAN AV,ATOLL AV
cross_street,NaN,N GAULT
lat,34.2124,34.1993
lon,-118.4092,-118.4203

In [6]:
display(samples["nibrs_2024_2025"].head(2).T)

,0,1
caseno,25245851,25245765
uniquenibrno,25245851_290_0,25245765_240_1
date_rptd,2025-12-31T00:00:00.000,2025-12-31T00:00:00.000
date_occ,2025-12-31T00:00:00.000,2025-12-29T00:00:00.000
time_occ,2120,1700
area,20,9
area_name,Olympic,Van Nuys
rpt_dist_no,2071,943
totaloffensecount,1,2
group,A,A
nibr_code,290,240
nibr_description,594(B)(2)(A) - PC - M - Vandalism Less Than $4...,487(D)(1) - PC - F - Grand Theft Auto - GTA -...
crime_against,Property,Property
premis_cd,RA,32
premis_desc,Single Family Home,Parking Lot / Garage / Drop Lot
weapon_used_cd,NaN,NaN
weapon_desc,NaN,NaN
status,14,40
status_desc,Cleared by Arrest - CA Filed,Investigation Continued
totalvictimcount,1,1
victim_shot,No,No
domestic_violence_crime,Yes,No
hate_crime,No,No
gang_related_crime,No,No
transit_related_crime,No,No
homeless_victim_crime,No,No
homeless_suspect_crime,No,No
homeless_arrestee_crime,No,No
location,1400 S Manhattan Pl,5600 Tilden Ave
lat,34.0463,34.1721
lon,-118.3102,-118.4474

In [ ]:
# Checking full row counts and data coverage
import requests

# Shows 1. Total published rows 2. Earliest occurrence date 3. Latest occurrence date
dataset_ids = {
    "legacy_2020_2024": "2nrs-mtv8",
    "nibrs_2024_2025": "y8y3-fqfu",
    "nibrs_2026_present": "k7nn-b2ep",
}

coverage_results = []

for dataset_name, dataset_id in dataset_ids.items():
    url = f"https://data.lacity.org/resource/{dataset_id}.json"

    parameters = {
        "$select": (
            "count(*) as row_count, "
            "min(date_occ) as min_date_occ, "
            "max(date_occ) as max_date_occ"
        )
    }

    response = requests.get(url, params=parameters, timeout=60)
    response.raise_for_status()

    result = response.json()[0]
    result["dataset_name"] = dataset_name
    coverage_results.append(result)

coverage = pd.DataFrame(coverage_results)

coverage["row_count"] = coverage["row_count"].astype(int)

coverage = coverage[
    ["dataset_name", "row_count", "min_date_occ", "max_date_occ"]
]

display(coverage)

,dataset_name,row_count,min_date_occ,max_date_occ
0,legacy_2020_2024,1004894,2020-01-01T00:00:00.000,2024-12-30T00:00:00.000
1,nibrs_2024_2025,255044,1920-11-24T00:00:00.000,2025-12-31T00:00:00.000
2,nibrs_2026_present,76278,1990-03-07T11:20:00.000,2026-06-27T23:57:39.000

In [10]:
# Compare occurrence dates with report dates
reporting_coverage_results = []

for dataset_name, dataset_id in dataset_ids.items():
    url = f"https://data.lacity.org/resource/{dataset_id}.json"

    parameters = {
        "$select": (
            "count(*) as row_count, "
            "min(date_rptd) as min_date_rptd, "
            "max(date_rptd) as max_date_rptd, "
            "min(date_occ) as min_date_occ, "
            "max(date_occ) as max_date_occ"
        )
    }

    response = requests.get(url, params=parameters, timeout=60)
    response.raise_for_status()

    result = response.json()[0]
    result["dataset_name"] = dataset_name
    reporting_coverage_results.append(result)

reporting_coverage = pd.DataFrame(reporting_coverage_results)

reporting_coverage["row_count"] = (
    reporting_coverage["row_count"].astype(int)
)

reporting_coverage = reporting_coverage[
    [
        "dataset_name",
        "row_count",
        "min_date_rptd",
        "max_date_rptd",
        "min_date_occ",
        "max_date_occ",
    ]
]

display(reporting_coverage)

,dataset_name,row_count,min_date_rptd,max_date_rptd,min_date_occ,max_date_occ
0,legacy_2020_2024,1004894,2020-01-01T00:00:00.000,2025-03-28T00:00:00.000,2020-01-01T00:00:00.000,2024-12-30T00:00:00.000
1,nibrs_2024_2025,255044,2024-02-05T00:00:00.000,2025-12-31T00:00:00.000,1920-11-24T00:00:00.000,2025-12-31T00:00:00.000
2,nibrs_2026_present,76278,2026-01-01T00:00:00.000,2026-06-27T23:57:55.000,1990-03-07T11:20:00.000,2026-06-27T23:57:39.000

In [11]:
# Downloading the complete raw files
from pathlib import Path

current_directory = Path.cwd()

if (current_directory / "README.md").exists():
    project_root = current_directory
else:
    project_root = current_directory.parent

raw_data_directory = project_root / "data" / "raw"
raw_data_directory.mkdir(parents=True, exist_ok=True)

print("Project root:", project_root)
print("Raw data directory:", raw_data_directory)

Project root: /Users/jonathanechoi/Documents/portfolio-projects/la-crime-reporting-change-dashboard
Raw data directory: /Users/jonathanechoi/Documents/portfolio-projects/la-crime-reporting-change-dashboard/data/raw

In [12]:
download_urls = {
    "lapd_legacy_2020_2024.csv": (
        "https://data.lacity.org/api/views/2nrs-mtv8/"
        "rows.csv?accessType=DOWNLOAD"
    ),
    "lapd_nibrs_2024_2025.csv": (
        "https://data.lacity.org/api/views/y8y3-fqfu/"
        "rows.csv?accessType=DOWNLOAD"
    ),
    "lapd_nibrs_2026_present.csv": (
        "https://data.lacity.org/api/views/k7nn-b2ep/"
        "rows.csv?accessType=DOWNLOAD"
    ),
}

In [13]:
for filename, url in download_urls.items():
    destination = raw_data_directory / filename

    if destination.exists():
        print(f"{filename} already exists. Skip download.")
        continue

    print(f"Downloading {filename}...")

    with requests.get(
        url,
        stream=True,
        timeout=(30, 300)
    ) as response:
        response.raise_for_status()

        with open(destination, "wb") as file:
            for chunk in response.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    file.write(chunk)

    size_mb = destination.stat().st_size / (1024 ** 2)
    print(f"Saved {filename}: {size_mb:.2f} MB")

Downloading lapd_legacy_2020_2024.csv...
Saved lapd_legacy_2020_2024.csv: 243.63 MB
Downloading lapd_nibrs_2024_2025.csv...
Saved lapd_nibrs_2024_2025.csv: 71.80 MB
Downloading lapd_nibrs_2026_present.csv...
Saved lapd_nibrs_2026_present.csv: 22.54 MB